options:
  logging: CLOUD_LOGGING_ONLY 

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/asktube:$COMMIT_SHA', '.']

  # Step 2: Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/asktube:$COMMIT_SHA']

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'asktube'  # Replace with your Cloud Run service name if needed
      - '--image'
      - 'gcr.io/$PROJECT_ID/asktube:$COMMIT_SHA'
      - '--region'
      - 'us-central1'  # Replace with your region
      - '--platform'
      - 'managed'
      - '--quiet'
      - '--update-env-vars'
      - 'OPENAI_API_KEY=projects/$PROJECT_ID/secrets/OPENAI_API_KEY:latest'

substitutions:
  _COMMIT_SHA: '${SHORT_SHA}'  # Mapping SHORT_SHA to COMMIT_SHA for consistency

images:
  - 'gcr.io/$PROJECT_ID/asktube:$COMMIT_SHA'
